version: "3.9"

services:
  web:
    build: .
    ports:
      - "8007:8000"
    env_file:
      - .env
    environment:
      SQLITE_PATH: /app/data/db.sqlite3
    volumes:
      - sqlite-data:/app/data
      - static-data:/app/staticfiles

volumes:
  sqlite-data:
  static-data:
